
# This file is automatically generated, you probably don't want to edit this

ciSingleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ciSingleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            deps = NULL,
            group = NULL,
            ciWidth = 95, ...) {

            super$initialize(
                package='PUBH5018',
                name='ciSingle',
                requiresData=TRUE,
                ...)

            private$..deps <- jmvcore::OptionVariables$new(
                "deps",
                deps)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.99)

            self$.addOption(private$..deps)
            self$.addOption(private$..group)
            self$.addOption(private$..ciWidth)
        }),
    active = list(
        deps = function() private$..deps$value,
        group = function() private$..group$value,
        ciWidth = function() private$..ciWidth$value),
    private = list(
        ..deps = NA,
        ..group = NA,
        ..ciWidth = NA)
)

ciSingleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        conflevel = function() private$.items[["conflevel"]],
        citable = function() private$.items[["citable"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Confidence interval for a mean")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="conflevel",
                title=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="citable",
                title="Confidence interval for a mean",
                rows="(deps)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="lb", 
                        `title`="Lower bound", 
                        `type`="number"),
                    list(
                        `name`="ub", 
                        `title`="Upper bound", 
                        `type`="number"))))}))

ciSingleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ciSingleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'PUBH5018',
                name = 'ciSingle',
                version = c(1,0,0),
                options = options,
                results = ciSingleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Confidence interval for a mean
#'
#' 
#' @param data .
#' @param deps .
#' @param group .
#' @param ciWidth .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$conflevel} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$citable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$citable$asDF}
#'
#' \code{as.data.frame(results$citable)}
#'
#' @export
ciSingle <- function(
    data,
    deps,
    group,
    ciWidth = 95) {

    if ( ! requireNamespace('jmvcore'))
        stop('ciSingle requires jmvcore to be installed (restart may be required)')

    if ( ! missing(deps)) deps <- jmvcore::resolveQuo(jmvcore::enquo(deps))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(deps), deps, NULL),
            `if`( ! missing(group), group, NULL))


    options <- ciSingleOptions$new(
        deps = deps,
        group = group,
        ciWidth = ciWidth)

    analysis <- ciSingleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
