
# This file is automatically generated, you probably don't want to edit this

ciSingleOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ciSingleOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            ciWidth = 95, ...) {

            super$initialize(
                package='PUBH5018',
                name='ciSingle',
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                default=95,
                min=50,
                max=99.99)

            self$.addOption(private$..dep)
            self$.addOption(private$..ciWidth)
        }),
    active = list(
        dep = function() private$..dep$value,
        ciWidth = function() private$..ciWidth$value),
    private = list(
        ..dep = NA,
        ..ciWidth = NA)
)

ciSingleResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Confidence interval for a single sample")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Confidence interval for a single sample"))}))

ciSingleBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "ciSingleBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'PUBH5018',
                name = 'ciSingle',
                version = c(1,0,0),
                options = options,
                results = ciSingleResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Confidence interval for a single sample
#'
#' 
#' @param data .
#' @param dep .
#' @param ciWidth .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#' }
#'
#' @export
ciSingle <- function(
    data,
    dep,
    ciWidth = 95) {

    if ( ! requireNamespace('jmvcore'))
        stop('ciSingle requires jmvcore to be installed (restart may be required)')

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL))


    options <- ciSingleOptions$new(
        dep = dep,
        ciWidth = ciWidth)

    analysis <- ciSingleClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
